### ISSUE TITLE
"Heist Finale" scaleform does not have a background.

### ISSUE THREAD

**Issue by CritteRo** [CritteRo/fivem-scaleform-lib#1]
"`CREATE_STAT_WALL`" needs a 'bgColourId' and 'sfxId' as input.

Combined with "`ADD_BACKGROUND_TO_WALL`"'s 'alpha' input should give the background of the scaleform, but it doesn't work.

I tried multiple values, but could not manage to get the background to appear.

**Comment by CritteRo** [comment]
Added `StartScreenEffect("HeistCelebEnd")` and `DrawRect(0.0, 0.0, 2.0, 2.0, 0, 92, 21, 160)` as a placeholders, until I can find the proper way of showing the Heist_Celebration background. This should work for now, but Green text does not look that good.

**Comment by PhilippRedel** [comment]
Can be closed because of your commit: https://github.com/CritteRo/fivem-scaleform-lib/commit/234b319e9398818b5b712e3d56dfa9d109d67be4

**Comment by CritteRo** [comment]
Background fixed in commit 4410baa07d9069b56e0f38f8a4a75c40796bc7f7 and 234b319e9398818b5b712e3d56dfa9d109d67be4
