### ISSUE TITLE
missionQuit can only be called one time

### ISSUE THREAD

**Issue by Scania01** [CritteRo/fivem-scaleform-lib#4]
Hey there! I can call missionQuit only one time. When I try to do a second time, I only hear the sounds, but it doesn't appear

**Comment by CritteRo** [comment]
Hi @Scania01 

I think I found the issue.
It looks like the "TRANSITION_OUT" function is causing the scaleform to not run the second time.

https://github.com/CritteRo/fivem-scaleform-lib/blob/93529648e0ee2b68375e90ee8776afbe8443aaef/critScaleforms/client/cl_scaleform_functions.lua#L115-L121

A fix would be to comment the entire function out (which I would do for now), but I think the scaleform needs a fade In function too.

**Comment by Scania01** [comment]
Okay 👍

**Comment by PhilippRedel** [comment]
Should be fixed with the #6
